SET DEFINE OFF;
SET SERVEROUTPUT ON;

--- 1. CATEGORY - add a new product category
   
CREATE OR REPLACE PROCEDURE HRDB.PROC_ADD_CATEGORY (
    P_CATEGORY_NAME IN VARCHAR2,
    P_DESCRIPTION   IN VARCHAR2 DEFAULT NULL
)
AS
BEGIN
    INSERT INTO HRDB.CATEGORY (CATEGORY_NAME, DESCRIPTION)
    VALUES (P_CATEGORY_NAME, P_DESCRIPTION);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Category added: ' || P_CATEGORY_NAME);
END PROC_ADD_CATEGORY;
/

--- 2. WAREHOUSE - register a new warehouse location
  
CREATE OR REPLACE PROCEDURE HRDB.PROC_ADD_WAREHOUSE (
    P_WAREHOUSE_NAME IN VARCHAR2,
    P_LOCATION       IN VARCHAR2,
    P_CITY           IN VARCHAR2,
    P_CAPACITY       IN NUMBER,
    P_MANAGER_NAME   IN VARCHAR2 DEFAULT NULL,
    P_PHONE          IN VARCHAR2 DEFAULT NULL
)
AS
BEGIN
    INSERT INTO HRDB.WAREHOUSE (
        WAREHOUSE_NAME, LOCATION_ADDRESS, CITY, CAPACITY_UNITS, MANAGER_NAME, PHONE
    ) VALUES (
        P_WAREHOUSE_NAME, P_LOCATION, P_CITY, P_CAPACITY, P_MANAGER_NAME, P_PHONE
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Warehouse added: ' || P_WAREHOUSE_NAME);
END PROC_ADD_WAREHOUSE;
/

--- 3. SUPPLIER - onboard a new supplier
   
CREATE OR REPLACE PROCEDURE HRDB.PROC_ADD_SUPPLIER (
    P_SUPPLIER_NAME  IN VARCHAR2,
    P_CONTACT_PERSON IN VARCHAR2 DEFAULT NULL,
    P_PHONE          IN VARCHAR2 DEFAULT NULL,
    P_EMAIL          IN VARCHAR2 DEFAULT NULL,
    P_CITY           IN VARCHAR2 DEFAULT NULL,
    P_COUNTRY        IN VARCHAR2 DEFAULT NULL,
    P_PAYMENT_TERMS  IN VARCHAR2 DEFAULT 'Net 30'
)
AS
BEGIN
    INSERT INTO HRDB.SUPPLIER (
        SUPPLIER_NAME, CONTACT_PERSON, PHONE, EMAIL, CITY, COUNTRY, PAYMENT_TERMS
    ) VALUES (
        P_SUPPLIER_NAME, P_CONTACT_PERSON, P_PHONE, P_EMAIL, P_CITY, P_COUNTRY, P_PAYMENT_TERMS
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Supplier added: ' || P_SUPPLIER_NAME);
END PROC_ADD_SUPPLIER;
/

--- 4. PRODUCT - register a new product/raw material to track
   
CREATE OR REPLACE PROCEDURE HRDB.PROC_ADD_PRODUCT (
    P_PRODUCT_CODE      IN VARCHAR2,
    P_PRODUCT_NAME      IN VARCHAR2,
    P_CATEGORY_ID       IN NUMBER,
    P_DEFAULT_SUPPLIER  IN NUMBER,
    P_UOM               IN VARCHAR2,
    P_UNIT_PRICE        IN NUMBER,
    P_REORDER_LEVEL     IN NUMBER DEFAULT 50,
    P_REORDER_QTY       IN NUMBER DEFAULT 100
)
AS
BEGIN
    INSERT INTO HRDB.PRODUCT (
        PRODUCT_CODE, PRODUCT_NAME, CATEGORY_ID, DEFAULT_SUPPLIER_ID,
        UNIT_OF_MEASURE, UNIT_PRICE, REORDER_LEVEL, REORDER_QTY
    ) VALUES (
        P_PRODUCT_CODE, P_PRODUCT_NAME, P_CATEGORY_ID, P_DEFAULT_SUPPLIER,
        P_UOM, P_UNIT_PRICE, P_REORDER_LEVEL, P_REORDER_QTY
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Product added: ' || P_PRODUCT_NAME || ' (' || P_PRODUCT_CODE || ')');
END PROC_ADD_PRODUCT;
/

--- 5. CUSTOMER - onboard a new distributor/retailer
   
CREATE OR REPLACE PROCEDURE HRDB.PROC_ADD_CUSTOMER (
    P_CUSTOMER_NAME  IN VARCHAR2,
    P_CUSTOMER_TYPE  IN VARCHAR2,
    P_CONTACT_PERSON IN VARCHAR2 DEFAULT NULL,
    P_PHONE          IN VARCHAR2 DEFAULT NULL,
    P_CITY           IN VARCHAR2 DEFAULT NULL,
    P_CREDIT_LIMIT   IN NUMBER DEFAULT 0
)
AS
BEGIN
    INSERT INTO HRDB.CUSTOMER (
        CUSTOMER_NAME, CUSTOMER_TYPE, CONTACT_PERSON, PHONE, CITY, CREDIT_LIMIT
    ) VALUES (
        P_CUSTOMER_NAME, P_CUSTOMER_TYPE, P_CONTACT_PERSON, P_PHONE, P_CITY, P_CREDIT_LIMIT
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Customer added: ' || P_CUSTOMER_NAME);
END PROC_ADD_CUSTOMER;
/

--- 6. STOCK - receive stock 
CREATE OR REPLACE PROCEDURE HRDB.PROC_RECEIVE_STOCK (
    P_PRODUCT_ID     IN NUMBER,
    P_WAREHOUSE_ID   IN NUMBER,
    P_QTY            IN NUMBER,
    P_UNIT_PRICE     IN NUMBER DEFAULT NULL,
    P_REFERENCE_TYPE IN VARCHAR2 DEFAULT 'MANUAL',
    P_REFERENCE_ID   IN NUMBER DEFAULT NULL
)
AS
    V_EXISTS NUMBER;
BEGIN
    IF P_QTY <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Quantity must be positive.');
    END IF;

    SELECT COUNT(*) INTO V_EXISTS FROM HRDB.STOCK
    WHERE PRODUCT_ID = P_PRODUCT_ID AND WAREHOUSE_ID = P_WAREHOUSE_ID;

    IF V_EXISTS = 0 THEN
        INSERT INTO HRDB.STOCK (PRODUCT_ID, WAREHOUSE_ID, QUANTITY_ON_HAND, LAST_UPDATED)
        VALUES (P_PRODUCT_ID, P_WAREHOUSE_ID, P_QTY, SYSDATE);
    ELSE
        UPDATE HRDB.STOCK
        SET QUANTITY_ON_HAND = QUANTITY_ON_HAND + P_QTY, LAST_UPDATED = SYSDATE
        WHERE PRODUCT_ID = P_PRODUCT_ID AND WAREHOUSE_ID = P_WAREHOUSE_ID;
    END IF;

    INSERT INTO HRDB.STOCK_TRANSACTION (
        PRODUCT_ID, WAREHOUSE_ID, TRANSACTION_TYPE, QUANTITY,
        TRANSACTION_DATE, REFERENCE_TYPE, REFERENCE_ID, UNIT_PRICE
    ) VALUES (
        P_PRODUCT_ID, P_WAREHOUSE_ID, 'IN', P_QTY, SYSDATE, P_REFERENCE_TYPE, P_REFERENCE_ID, P_UNIT_PRICE
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Received ' || P_QTY || ' units of product ' || P_PRODUCT_ID);
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END PROC_RECEIVE_STOCK;
/

--- 7. STOCK_TRANSACTION 
CREATE OR REPLACE PROCEDURE HRDB.PROC_ISSUE_STOCK (
    P_PRODUCT_ID     IN NUMBER,
    P_WAREHOUSE_ID   IN NUMBER,
    P_QTY            IN NUMBER,
    P_REFERENCE_TYPE IN VARCHAR2 DEFAULT 'MANUAL',
    P_REFERENCE_ID   IN NUMBER DEFAULT NULL
)
AS
    V_CURRENT_QTY NUMBER;
BEGIN
    IF P_QTY <= 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Quantity must be positive.');
    END IF;

    SELECT QUANTITY_ON_HAND INTO V_CURRENT_QTY FROM HRDB.STOCK
    WHERE PRODUCT_ID = P_PRODUCT_ID AND WAREHOUSE_ID = P_WAREHOUSE_ID
    FOR UPDATE;

    IF V_CURRENT_QTY < P_QTY THEN
        RAISE_APPLICATION_ERROR(-20003,
            'Insufficient stock. Available: ' || V_CURRENT_QTY || ', Requested: ' || P_QTY);
    END IF;

    UPDATE HRDB.STOCK
    SET QUANTITY_ON_HAND = QUANTITY_ON_HAND - P_QTY, LAST_UPDATED = SYSDATE
    WHERE PRODUCT_ID = P_PRODUCT_ID AND WAREHOUSE_ID = P_WAREHOUSE_ID;

    INSERT INTO HRDB.STOCK_TRANSACTION (
        PRODUCT_ID, WAREHOUSE_ID, TRANSACTION_TYPE, QUANTITY,
        TRANSACTION_DATE, REFERENCE_TYPE, REFERENCE_ID
    ) VALUES (
        P_PRODUCT_ID, P_WAREHOUSE_ID, 'OUT', P_QTY, SYSDATE, P_REFERENCE_TYPE, P_REFERENCE_ID
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Issued ' || P_QTY || ' units of product ' || P_PRODUCT_ID);
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END PROC_ISSUE_STOCK;
/

--- 8. PURCHASE_ORDER
CREATE OR REPLACE PROCEDURE HRDB.PROC_CREATE_PURCHASE_ORDER (
    P_SUPPLIER_ID    IN  NUMBER,
    P_WAREHOUSE_ID   IN  NUMBER,
    P_EXPECTED_DAYS  IN  NUMBER DEFAULT 7,
    P_PO_ID          OUT NUMBER
)
AS
BEGIN
    INSERT INTO HRDB.PURCHASE_ORDER (
        PO_NUMBER, SUPPLIER_ID, WAREHOUSE_ID, ORDER_DATE, EXPECTED_DATE, STATUS, TOTAL_AMOUNT
    ) VALUES (
        'PO-' || HRDB.PO_NUMBER_SEQ.NEXTVAL, P_SUPPLIER_ID, P_WAREHOUSE_ID,
        SYSDATE, SYSDATE + P_EXPECTED_DAYS, 'PENDING', 0
    ) RETURNING PO_ID INTO P_PO_ID;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Purchase Order created, ID: ' || P_PO_ID);
END PROC_CREATE_PURCHASE_ORDER;
/

--- 9. PURCHASE_ORDER_DETAIL 
CREATE OR REPLACE PROCEDURE HRDB.PROC_ADD_PO_DETAIL (
    P_PO_ID      IN NUMBER,
    P_PRODUCT_ID IN NUMBER,
    P_QTY        IN NUMBER,
    P_UNIT_PRICE IN NUMBER
)
AS
BEGIN
    INSERT INTO HRDB.PURCHASE_ORDER_DETAIL (PO_ID, PRODUCT_ID, ORDERED_QTY, UNIT_PRICE)
    VALUES (P_PO_ID, P_PRODUCT_ID, P_QTY, P_UNIT_PRICE);

    UPDATE HRDB.PURCHASE_ORDER
    SET TOTAL_AMOUNT = NVL(TOTAL_AMOUNT, 0) + (P_QTY * P_UNIT_PRICE)
    WHERE PO_ID = P_PO_ID;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Added ' || P_QTY || ' units of product ' || P_PRODUCT_ID || ' to PO ' || P_PO_ID);
END PROC_ADD_PO_DETAIL;
/

--- 10. SALES_ORDER -
CREATE OR REPLACE PROCEDURE HRDB.PROC_CREATE_SALES_ORDER (
    P_CUSTOMER_ID  IN  NUMBER,
    P_WAREHOUSE_ID IN  NUMBER,
    P_SO_ID        OUT NUMBER
)
AS
BEGIN
    INSERT INTO HRDB.SALES_ORDER (
        SO_NUMBER, CUSTOMER_ID, WAREHOUSE_ID, ORDER_DATE, STATUS, TOTAL_AMOUNT
    ) VALUES (
        'SO-' || HRDB.SO_NUMBER_SEQ.NEXTVAL, P_CUSTOMER_ID, P_WAREHOUSE_ID,
        SYSDATE, 'PENDING', 0
    ) RETURNING SO_ID INTO P_SO_ID;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Sales Order created, ID: ' || P_SO_ID);
END PROC_CREATE_SALES_ORDER;
/

--- 11. SALES_ORDER_DETAIL 
CREATE OR REPLACE PROCEDURE HRDB.PROC_ADD_SO_DETAIL (
    P_SO_ID        IN NUMBER,
    P_PRODUCT_ID   IN NUMBER,
    P_QTY          IN NUMBER,
    P_UNIT_PRICE   IN NUMBER,
    P_WAREHOUSE_ID IN NUMBER
)
AS
BEGIN
    INSERT INTO HRDB.SALES_ORDER_DETAIL (SO_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
    VALUES (P_SO_ID, P_PRODUCT_ID, P_QTY, P_UNIT_PRICE);

    UPDATE HRDB.SALES_ORDER
    SET TOTAL_AMOUNT = NVL(TOTAL_AMOUNT, 0) + (P_QTY * P_UNIT_PRICE)
    WHERE SO_ID = P_SO_ID;

    -- Reuses the issue-stock procedure
    -- reduces real warehouse stock, referencing this sales order
    HRDB.PROC_ISSUE_STOCK(P_PRODUCT_ID, P_WAREHOUSE_ID, P_QTY, 'SALES_ORDER', P_SO_ID);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Added ' || P_QTY || ' units of product ' || P_PRODUCT_ID || ' to SO ' || P_SO_ID);
END PROC_ADD_SO_DETAIL;
/

--- 12. LOW_STOCK_ALERT 
CREATE OR REPLACE PROCEDURE HRDB.PROC_UPDATE_ALERT_STATUS (
    P_ALERT_ID  IN NUMBER,
    P_STATUS    IN VARCHAR2   -- 'ACKNOWLEDGED' or 'RESOLVED'
)
AS
BEGIN
    UPDATE HRDB.LOW_STOCK_ALERT
    SET STATUS = P_STATUS
    WHERE ALERT_ID = P_ALERT_ID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Alert ID ' || P_ALERT_ID || ' not found.');
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Alert ' || P_ALERT_ID || ' updated to status: ' || P_STATUS);
END PROC_UPDATE_ALERT_STATUS;
/

--- TEST ALL 12 PROCEDURES

SET SERVEROUTPUT ON;

BEGIN
    HRDB.PROC_ADD_CATEGORY('Test Category', 'For testing purposes');
    HRDB.PROC_ADD_WAREHOUSE('Test Warehouse', 'Test Street', 'Lahore', 10000, 'Test Manager', '03001112233');
    HRDB.PROC_ADD_SUPPLIER('Test Supplier Co', 'Test Contact', '03009998888', 'test@supplier.com', 'Lahore', 'Pakistan');
    HRDB.PROC_ADD_CUSTOMER('Test Distributor', 'DISTRIBUTOR', 'Test Manager', '03007776666', 'Karachi', 500000);
END;
/

-- PRODUCT needs valid category/supplier IDs - grab existing ones
DECLARE
    V_CAT_ID  NUMBER;
    V_SUP_ID  NUMBER;
BEGIN
    SELECT MAX(CATEGORY_ID) INTO V_CAT_ID FROM HRDB.CATEGORY;
    SELECT MAX(SUPPLIER_ID) INTO V_SUP_ID FROM HRDB.SUPPLIER;

    HRDB.PROC_ADD_PRODUCT('SKU-TEST01', 'Test Product', V_CAT_ID, V_SUP_ID, 'PIECE', 100, 20, 100);
END;
/

-- Purchase Order flow: create header, then add line items
DECLARE
    V_PO_ID NUMBER;
BEGIN
    HRDB.PROC_CREATE_PURCHASE_ORDER(P_SUPPLIER_ID => 1, P_WAREHOUSE_ID => 1, P_PO_ID => V_PO_ID);
    HRDB.PROC_ADD_PO_DETAIL(V_PO_ID, 1, 100, 250);
    HRDB.PROC_ADD_PO_DETAIL(V_PO_ID, 2, 50, 300);
END;
/

-- Sales Order flow: create header, then add line items (which also
-- issues real stock out - watch STOCK quantity drop)
DECLARE
    V_SO_ID NUMBER;
BEGIN
    HRDB.PROC_CREATE_SALES_ORDER(P_CUSTOMER_ID => 1, P_WAREHOUSE_ID => 1, P_SO_ID => V_SO_ID);
    HRDB.PROC_ADD_SO_DETAIL(V_SO_ID, 1, 10, 400, 1);
END;
/

-- Update an alert status (pick any existing ALERT_ID)
-- BEGIN
--     HRDB.PROC_UPDATE_ALERT_STATUS(P_ALERT_ID => 1, P_STATUS => 'ACKNOWLEDGED');
-- END;
-- /

-- Verify
SELECT * FROM HRDB.CATEGORY WHERE CATEGORY_NAME = 'Test Category';
SELECT * FROM HRDB.PRODUCT WHERE PRODUCT_CODE = 'SKU-TEST01';