--- 1. SUPPLIER - who you buy raw materials/products from

CREATE TABLE HRDB.SUPPLIER (
    SUPPLIER_ID       NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUPPLIER_NAME     VARCHAR2(150)   NOT NULL,
    CONTACT_PERSON    VARCHAR2(100),
    PHONE             VARCHAR2(20),
    EMAIL             VARCHAR2(100),
    ADDRESS           VARCHAR2(200),
    CITY              VARCHAR2(50),
    COUNTRY           VARCHAR2(50),
    SUPPLIER_RATING   NUMBER(2,1)     CHECK (SUPPLIER_RATING BETWEEN 0 AND 5),
    PAYMENT_TERMS     VARCHAR2(50),                 -- e.g. 'Net 30', 'COD'
    STATUS            VARCHAR2(10)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CREATED_DATE      DATE            DEFAULT SYSDATE
);

---- 2. WAREHOUSE - physical storage locations

CREATE TABLE HRDB.WAREHOUSE (
    WAREHOUSE_ID      NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WAREHOUSE_NAME    VARCHAR2(100)   NOT NULL,
    LOCATION_ADDRESS  VARCHAR2(200),
    CITY              VARCHAR2(50),
    CAPACITY_UNITS    NUMBER(12),                   -- max storage capacity
    MANAGER_NAME      VARCHAR2(100),
    PHONE             VARCHAR2(20),
    STATUS            VARCHAR2(10)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CREATED_DATE      DATE            DEFAULT SYSDATE
);

--- 3. CATEGORY - product/material classification

CREATE TABLE HRDB.CATEGORY (
    CATEGORY_ID       NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATEGORY_NAME     VARCHAR2(100)   NOT NULL,
    DESCRIPTION       VARCHAR2(300)
);

 --- 4. PRODUCT - raw materials / finished goods being tracked
   
CREATE TABLE HRDB.PRODUCT (
    PRODUCT_ID        NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_CODE      VARCHAR2(30)    NOT NULL UNIQUE,   -- SKU
    PRODUCT_NAME      VARCHAR2(150)   NOT NULL,
    CATEGORY_ID       NUMBER(10)      NOT NULL,
    DEFAULT_SUPPLIER_ID NUMBER(10),
    UNIT_OF_MEASURE   VARCHAR2(20),                  -- KG, LITER, PIECE, BOX
    UNIT_PRICE        NUMBER(12,2)    NOT NULL,
    REORDER_LEVEL     NUMBER(10)      DEFAULT 50,    -- trigger threshold
    REORDER_QTY       NUMBER(10)      DEFAULT 100,   -- how much to reorder
    STATUS            VARCHAR2(10)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE','DISCONTINUED')),
    CREATED_DATE      DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES HRDB.CATEGORY(CATEGORY_ID),
    CONSTRAINT FK_PRODUCT_SUPPLIER FOREIGN KEY (DEFAULT_SUPPLIER_ID) REFERENCES HRDB.SUPPLIER(SUPPLIER_ID)
);

--- 5. STOCK - CURRENT quantity on hand, per product per warehouse
   
CREATE TABLE HRDB.STOCK (
    STOCK_ID          NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID        NUMBER(10)      NOT NULL,
    WAREHOUSE_ID      NUMBER(10)      NOT NULL,
    QUANTITY_ON_HAND  NUMBER(12)      DEFAULT 0 NOT NULL,
    LAST_UPDATED      DATE            DEFAULT SYSDATE,
    CONSTRAINT UK_STOCK_PRODUCT_WH UNIQUE (PRODUCT_ID, WAREHOUSE_ID),
    CONSTRAINT FK_STOCK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES HRDB.PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_STOCK_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES HRDB.WAREHOUSE(WAREHOUSE_ID)
);

--- 6. STOCK_TRANSACTION - the full movement HISTORY 
   --- Every single stock-in, stock-out, transfer, or adjustment is one row.
 
CREATE TABLE HRDB.STOCK_TRANSACTION (
    TRANSACTION_ID    NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID        NUMBER(10)      NOT NULL,
    WAREHOUSE_ID      NUMBER(10)      NOT NULL,
    TRANSACTION_TYPE  VARCHAR2(10)    NOT NULL CHECK (TRANSACTION_TYPE IN ('IN','OUT','ADJUST')),
    QUANTITY          NUMBER(10)      NOT NULL,
    TRANSACTION_DATE  DATE            NOT NULL,
    REFERENCE_TYPE    VARCHAR2(20),                  -- 'PURCHASE_ORDER','SALES_ORDER','MANUAL'
    REFERENCE_ID      NUMBER,                        -- links to PO_ID or SO_ID
    UNIT_PRICE        NUMBER(12,2),
    CREATED_BY        VARCHAR2(50)    DEFAULT USER,
    CREATED_DATE      DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_TXN_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES HRDB.PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_TXN_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES HRDB.WAREHOUSE(WAREHOUSE_ID)
);

--- 7. PURCHASE_ORDER - what you ordered from a supplier
   
CREATE TABLE HRDB.PURCHASE_ORDER (
    PO_ID             NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUPPLIER_ID       NUMBER(10)      NOT NULL,
    WAREHOUSE_ID      NUMBER(10)      NOT NULL,
    ORDER_DATE        DATE            NOT NULL,
    EXPECTED_DATE     DATE,
    RECEIVED_DATE     DATE,
    STATUS            VARCHAR2(15)    DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING','PARTIAL','RECEIVED','CANCELLED')),
    TOTAL_AMOUNT      NUMBER(14,2),
    CREATED_BY        VARCHAR2(50)    DEFAULT USER,
    CONSTRAINT FK_PO_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES HRDB.SUPPLIER(SUPPLIER_ID),
    CONSTRAINT FK_PO_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES HRDB.WAREHOUSE(WAREHOUSE_ID)
);

--- 8. PURCHASE_ORDER_DETAIL - line items within a purchase order
   
CREATE TABLE HRDB.PURCHASE_ORDER_DETAIL (
    PO_DETAIL_ID      NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PO_ID             NUMBER(10)      NOT NULL,
    PRODUCT_ID        NUMBER(10)      NOT NULL,
    ORDERED_QTY       NUMBER(10)      NOT NULL,
    RECEIVED_QTY      NUMBER(10)      DEFAULT 0,
    UNIT_PRICE        NUMBER(12,2)    NOT NULL,
    CONSTRAINT FK_POD_PO FOREIGN KEY (PO_ID) REFERENCES HRDB.PURCHASE_ORDER(PO_ID),
    CONSTRAINT FK_POD_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES HRDB.PRODUCT(PRODUCT_ID)
);

--- 9. CUSTOMER - distributors / retailers you sell/distribute to
   
CREATE TABLE HRDB.CUSTOMER (
    CUSTOMER_ID       NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_NAME     VARCHAR2(150)   NOT NULL,
    CUSTOMER_TYPE     VARCHAR2(20)    CHECK (CUSTOMER_TYPE IN ('DISTRIBUTOR','RETAILER','WHOLESALER')),
    CONTACT_PERSON    VARCHAR2(100),
    PHONE             VARCHAR2(20),
    CITY              VARCHAR2(50),
    CREDIT_LIMIT      NUMBER(14,2)    DEFAULT 0,
    STATUS            VARCHAR2(10)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CREATED_DATE      DATE            DEFAULT SYSDATE
);
 
 
--- 10. SALES_ORDER - what a distributor/customer ordered from you
  
CREATE TABLE HRDB.SALES_ORDER (
    SO_ID             NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID       NUMBER(10)      NOT NULL,
    WAREHOUSE_ID      NUMBER(10)      NOT NULL,
    ORDER_DATE        DATE            NOT NULL,
    DELIVERY_DATE     DATE,
    STATUS            VARCHAR2(15)    DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING','SHIPPED','DELIVERED','CANCELLED')),
    TOTAL_AMOUNT      NUMBER(14,2),
    CONSTRAINT FK_SO_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES HRDB.CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_SO_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES HRDB.WAREHOUSE(WAREHOUSE_ID)
);
 
--- 11. SALES_ORDER_DETAIL - line items within a sales order
   
CREATE TABLE HRDB.SALES_ORDER_DETAIL (
    SO_DETAIL_ID      NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SO_ID             NUMBER(10)      NOT NULL,
    PRODUCT_ID        NUMBER(10)      NOT NULL,
    QUANTITY          NUMBER(10)      NOT NULL,
    UNIT_PRICE        NUMBER(12,2)    NOT NULL,
    CONSTRAINT FK_SOD_SO FOREIGN KEY (SO_ID) REFERENCES HRDB.SALES_ORDER(SO_ID),
    CONSTRAINT FK_SOD_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES HRDB.PRODUCT(PRODUCT_ID)
);
 
--- 12. LOW_STOCK_ALERT - auto-populated by a TRIGGER when stock drops

Create TABLE HRDB.LOW_STOCK_ALERT (
    ALERT_ID          NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID        NUMBER(10)      NOT NULL,
    WAREHOUSE_ID      NUMBER(10)      NOT NULL,
    CURRENT_QTY       NUMBER(12),
    REORDER_LEVEL     NUMBER(10),
    ALERT_DATE        DATE            DEFAULT SYSDATE,
    STATUS            VARCHAR2(15)    DEFAULT 'OPEN' CHECK (STATUS IN ('OPEN','ACKNOWLEDGED','RESOLVED')),
    CONSTRAINT FK_ALERT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES HRDB.PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_ALERT_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES HRDB.WAREHOUSE(WAREHOUSE_ID)
);

--- Indexes

CREATE INDEX IDX_TXN_PRODUCT_WH_DATE ON HRDB.STOCK_TRANSACTION(PRODUCT_ID, WAREHOUSE_ID, TRANSACTION_DATE);
CREATE INDEX IDX_TXN_DATE            ON HRDB.STOCK_TRANSACTION(TRANSACTION_DATE);
CREATE INDEX IDX_TXN_TYPE            ON HRDB.STOCK_TRANSACTION(TRANSACTION_TYPE);
CREATE INDEX IDX_POD_PO              ON HRDB.PURCHASE_ORDER_DETAIL(PO_ID);
CREATE INDEX IDX_SOD_SO              ON HRDB.SALES_ORDER_DETAIL(SO_ID);
CREATE INDEX IDX_PRODUCT_CATEGORY    ON HRDB.PRODUCT(CATEGORY_ID);

SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'HRDB' ORDER BY TABLE_NAME;

SELECT TABLE_NAME FROM ALL_TABLES 
WHERE OWNER = 'HRDB' 
AND TABLE_NAME IN ('SUPPLIER','WAREHOUSE','STOCK','STOCK_TRANSACTION',
                    'SALES_ORDER','SALES_ORDER_DETAIL')
ORDER BY TABLE_NAME;



 
 
 