--- PHASE 6: FUNCTIONS - reusable calculations

SET DEFINE OFF;
SET SERVEROUTPUT ON;

--- FUNCTION 1: Current stock value (quantity x unit price) for a
---   product in a specific warehouse
  
CREATE OR REPLACE FUNCTION HRDB.FN_GET_STOCK_VALUE (
    P_PRODUCT_ID   IN NUMBER,
    P_WAREHOUSE_ID IN NUMBER
) RETURN NUMBER
AS
    V_QTY   NUMBER;
    V_PRICE NUMBER;
BEGIN
    SELECT QUANTITY_ON_HAND INTO V_QTY
    FROM HRDB.STOCK
    WHERE PRODUCT_ID = P_PRODUCT_ID AND WAREHOUSE_ID = P_WAREHOUSE_ID;

    SELECT UNIT_PRICE INTO V_PRICE
    FROM HRDB.PRODUCT
    WHERE PRODUCT_ID = P_PRODUCT_ID;

    RETURN ROUND(V_QTY * V_PRICE, 2);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END FN_GET_STOCK_VALUE;
/

--- FUNCTION 2: Average daily consumption (OUT transactions) over the
---   last N days for a product in a warehouse
  
CREATE OR REPLACE FUNCTION HRDB.FN_AVG_DAILY_CONSUMPTION (
    P_PRODUCT_ID   IN NUMBER,
    P_WAREHOUSE_ID IN NUMBER,
    P_DAYS         IN NUMBER DEFAULT 90
) RETURN NUMBER
AS
    V_TOTAL_OUT  NUMBER;
    V_LATEST_DT  DATE;
BEGIN
    SELECT MAX(TRANSACTION_DATE) INTO V_LATEST_DT FROM HRDB.STOCK_TRANSACTION;

    SELECT NVL(SUM(QUANTITY), 0) INTO V_TOTAL_OUT
    FROM HRDB.STOCK_TRANSACTION
    WHERE PRODUCT_ID = P_PRODUCT_ID
      AND WAREHOUSE_ID = P_WAREHOUSE_ID
      AND TRANSACTION_TYPE = 'OUT'
      AND TRANSACTION_DATE >= V_LATEST_DT - P_DAYS;

    RETURN ROUND(V_TOTAL_OUT / P_DAYS, 2);
END FN_AVG_DAILY_CONSUMPTION;
/

--- FUNCTION 3: Days of supply remaining = current stock / avg daily consumption.

CREATE OR REPLACE FUNCTION HRDB.FN_DAYS_OF_SUPPLY (
    P_PRODUCT_ID   IN NUMBER,
    P_WAREHOUSE_ID IN NUMBER
) RETURN NUMBER
AS
    V_QTY         NUMBER;
    V_AVG_DAILY   NUMBER;
BEGIN
    SELECT QUANTITY_ON_HAND INTO V_QTY
    FROM HRDB.STOCK
    WHERE PRODUCT_ID = P_PRODUCT_ID AND WAREHOUSE_ID = P_WAREHOUSE_ID;

    V_AVG_DAILY := HRDB.FN_AVG_DAILY_CONSUMPTION(P_PRODUCT_ID, P_WAREHOUSE_ID);

    IF V_AVG_DAILY IS NULL OR V_AVG_DAILY = 0 THEN
        RETURN NULL;  -- can't estimate - no recent consumption
    ELSE
        RETURN ROUND(V_QTY / V_AVG_DAILY, 1);
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END FN_DAYS_OF_SUPPLY;
/

--- TEST THE FUNCTIONS

SET SERVEROUTPUT ON;

DECLARE
    V_VALUE NUMBER;
    V_AVG   NUMBER;
    V_DAYS  NUMBER;
BEGIN
    V_VALUE := HRDB.FN_GET_STOCK_VALUE(1, 1);
    V_AVG   := HRDB.FN_AVG_DAILY_CONSUMPTION(1, 1);
    V_DAYS  := HRDB.FN_DAYS_OF_SUPPLY(1, 1);

    DBMS_OUTPUT.PUT_LINE('Stock Value          : ' || V_VALUE);
    DBMS_OUTPUT.PUT_LINE('Avg Daily Consumption: ' || V_AVG);
    DBMS_OUTPUT.PUT_LINE('Days of Supply Left  : ' || V_DAYS);
END;
/

SELECT
    PRODUCT_ID,
    WAREHOUSE_ID,
    QUANTITY_ON_HAND,
    HRDB.FN_GET_STOCK_VALUE(PRODUCT_ID, WAREHOUSE_ID) AS STOCK_VALUE,
    HRDB.FN_DAYS_OF_SUPPLY(PRODUCT_ID, WAREHOUSE_ID) AS DAYS_LEFT
FROM HRDB.STOCK
WHERE WAREHOUSE_ID = 1
FETCH FIRST 10 ROWS ONLY;