--- PHASE 10: VIEWS - reusable, reporting-ready
    
SET DEFINE OFF;
SET SERVEROUTPUT ON;

--- VIEW 1: Supplier performance - order counts, value supplied, and on-time delivery rate

CREATE OR REPLACE VIEW HRDB.V_SUPPLIER_PERFORMANCE AS
SELECT
    s.SUPPLIER_ID,
    s.SUPPLIER_NAME,
    s.CITY,
    s.SUPPLIER_RATING,
    COUNT(po.PO_ID)                                            AS TOTAL_ORDERS,
    SUM(CASE WHEN po.STATUS = 'RECEIVED' THEN 1 ELSE 0 END)    AS RECEIVED_ORDERS,
    SUM(CASE WHEN po.STATUS = 'CANCELLED' THEN 1 ELSE 0 END)   AS CANCELLED_ORDERS,
    ROUND(SUM(CASE WHEN po.STATUS = 'RECEIVED'
                    AND po.RECEIVED_DATE <= po.EXPECTED_DATE THEN 1 ELSE 0 END)
          / NULLIF(SUM(CASE WHEN po.STATUS = 'RECEIVED' THEN 1 ELSE 0 END), 0) * 100, 1)
                                                                 AS ON_TIME_PCT,
    ROUND(SUM(NVL(po.TOTAL_AMOUNT,0)), 2)                       AS TOTAL_VALUE_SUPPLIED
FROM HRDB.SUPPLIER s
LEFT JOIN HRDB.PURCHASE_ORDER po ON po.SUPPLIER_ID = s.SUPPLIER_ID
GROUP BY s.SUPPLIER_ID, s.SUPPLIER_NAME, s.CITY, s.SUPPLIER_RATING;

-- Usage
SELECT * FROM HRDB.V_SUPPLIER_PERFORMANCE
ORDER BY TOTAL_VALUE_SUPPLIED DESC
FETCH FIRST 10 ROWS ONLY;


/* ----------------------------------------------------------------------
   VIEW 2: Warehouse stock summary - current holdings + open alerts
   ---------------------------------------------------------------------- */
CREATE OR REPLACE VIEW HRDB.V_WAREHOUSE_STOCK_SUMMARY AS
SELECT
    w.WAREHOUSE_ID,
    w.WAREHOUSE_NAME,
    w.CITY,
    COUNT(DISTINCT st.PRODUCT_ID)                              AS DISTINCT_PRODUCTS,
    SUM(st.QUANTITY_ON_HAND)                                   AS TOTAL_UNITS,
    ROUND(SUM(st.QUANTITY_ON_HAND * p.UNIT_PRICE), 2)          AS TOTAL_STOCK_VALUE,
    (SELECT COUNT(*) FROM HRDB.LOW_STOCK_ALERT la
     WHERE la.WAREHOUSE_ID = w.WAREHOUSE_ID AND la.STATUS = 'OPEN') AS OPEN_ALERTS
FROM HRDB.WAREHOUSE w
LEFT JOIN HRDB.STOCK st ON st.WAREHOUSE_ID = w.WAREHOUSE_ID
LEFT JOIN HRDB.PRODUCT p ON p.PRODUCT_ID = st.PRODUCT_ID
GROUP BY w.WAREHOUSE_ID, w.WAREHOUSE_NAME, w.CITY;

-- Usage
SELECT * FROM HRDB.V_WAREHOUSE_STOCK_SUMMARY ORDER BY TOTAL_STOCK_VALUE DESC;


/* ----------------------------------------------------------------------
   VIEW 3: Product movement - total IN vs OUT, current stock, turnover
   ---------------------------------------------------------------------- */
CREATE OR REPLACE VIEW HRDB.V_PRODUCT_MOVEMENT AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY_ID,
    NVL(SUM(CASE WHEN t.TRANSACTION_TYPE = 'IN'  THEN t.QUANTITY END), 0) AS TOTAL_RECEIVED,
    NVL(SUM(CASE WHEN t.TRANSACTION_TYPE = 'OUT' THEN t.QUANTITY END), 0) AS TOTAL_ISSUED,
    (SELECT SUM(QUANTITY_ON_HAND) FROM HRDB.STOCK s WHERE s.PRODUCT_ID = p.PRODUCT_ID) AS CURRENT_TOTAL_STOCK
FROM HRDB.PRODUCT p
LEFT JOIN HRDB.STOCK_TRANSACTION t ON t.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY_ID;

-- Usage: fastest-moving products (highest OUT quantity)
SELECT * FROM HRDB.V_PRODUCT_MOVEMENT
ORDER BY TOTAL_ISSUED DESC
FETCH FIRST 10 ROWS ONLY;


--- VIEW 4: Low stock dashboard - open alerts with full context
  
CREATE OR REPLACE VIEW HRDB.V_LOW_STOCK_DASHBOARD AS
SELECT
    a.ALERT_ID,
    p.PRODUCT_NAME,
    w.WAREHOUSE_NAME,
    a.CURRENT_QTY,
    a.REORDER_LEVEL,
    p.REORDER_QTY AS SUGGESTED_ORDER_QTY,
    sup.SUPPLIER_NAME AS DEFAULT_SUPPLIER,
    a.ALERT_DATE,
    a.STATUS
FROM HRDB.LOW_STOCK_ALERT a
JOIN HRDB.PRODUCT p ON p.PRODUCT_ID = a.PRODUCT_ID
JOIN HRDB.WAREHOUSE w ON w.WAREHOUSE_ID = a.WAREHOUSE_ID
LEFT JOIN HRDB.SUPPLIER sup ON sup.SUPPLIER_ID = p.DEFAULT_SUPPLIER_ID;

-- Usage
SELECT * FROM HRDB.V_LOW_STOCK_DASHBOARD WHERE STATUS = 'OPEN' ORDER BY ALERT_DATE;