--- STEP 1: Additional indexes

CREATE INDEX HRDB.IDX_PO_SUPPLIER   ON HRDB.PURCHASE_ORDER(SUPPLIER_ID);
CREATE INDEX HRDB.IDX_PO_WAREHOUSE  ON HRDB.PURCHASE_ORDER(WAREHOUSE_ID);
CREATE INDEX HRDB.IDX_PO_DATE       ON HRDB.PURCHASE_ORDER(ORDER_DATE);
 
CREATE INDEX HRDB.IDX_SO_CUSTOMER   ON HRDB.SALES_ORDER(CUSTOMER_ID);
CREATE INDEX HRDB.IDX_SO_WAREHOUSE  ON HRDB.SALES_ORDER(WAREHOUSE_ID);
CREATE INDEX HRDB.IDX_SO_DATE       ON HRDB.SALES_ORDER(ORDER_DATE);
 
CREATE INDEX HRDB.IDX_ALERT_STATUS  ON HRDB.LOW_STOCK_ALERT(STATUS);
CREATE INDEX HRDB.IDX_STOCK_PRODUCT ON HRDB.STOCK(PRODUCT_ID);

--- STEP 2: Gather statistics
BEGIN
    DBMS_STATS.GATHER_TABLE_STATS('HRDB', 'STOCK_TRANSACTION');
    DBMS_STATS.GATHER_TABLE_STATS('HRDB', 'PRODUCT');
    DBMS_STATS.GATHER_TABLE_STATS('HRDB', 'STOCK');
    DBMS_STATS.GATHER_TABLE_STATS('HRDB', 'PURCHASE_ORDER');
    DBMS_STATS.GATHER_TABLE_STATS('HRDB', 'SALES_ORDER');
    DBMS_STATS.GATHER_TABLE_STATS('HRDB', 'SUPPLIER');
    DBMS_STATS.GATHER_TABLE_STATS('HRDB', 'CUSTOMER');
    DBMS_OUTPUT.PUT_LINE('Statistics gathered for all major tables.');
END;
/

--- STEP 3: VERIFY - EXPLAIN PLAN before/after comparison
   
-- (a) Filter by PRODUCT_ID on the 1-million-row table
--     Expect: INDEX RANGE SCAN on IDX_TXN_PRODUCT_WH_DATE (from Phase 1)
EXPLAIN PLAN FOR
SELECT * FROM HRDB.STOCK_TRANSACTION
WHERE PRODUCT_ID = 100;
 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
 
 
-- (b) Filter by TRANSACTION_DATE range on the 1-million-row table
--     Expect: INDEX RANGE SCAN on IDX_TXN_DATE
EXPLAIN PLAN FOR
SELECT * FROM HRDB.STOCK_TRANSACTION
WHERE TRANSACTION_DATE BETWEEN DATE '2023-01-01' AND DATE '2023-01-31';
 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
 
 
-- (c) Filter by PRODUCT_ID + WAREHOUSE_ID + DATE together
--     Expect: INDEX RANGE SCAN using the composite index (most efficient)
EXPLAIN PLAN FOR
SELECT * FROM HRDB.STOCK_TRANSACTION
WHERE PRODUCT_ID = 100 AND WAREHOUSE_ID = 2
AND TRANSACTION_DATE BETWEEN DATE '2023-01-01' AND DATE '2023-12-31';
 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
 
 
-- (d) Filter by SUPPLIER_ID on PURCHASE_ORDER
--     Expect: INDEX RANGE SCAN on IDX_PO_SUPPLIER
EXPLAIN PLAN FOR
SELECT * FROM HRDB.PURCHASE_ORDER
WHERE SUPPLIER_ID = 5;
 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
 
 
-- (e) A query with NO usable index (deliberately, for comparison)
--     Expect: TABLE ACCESS FULL - this shows what "bad" looks like
EXPLAIN PLAN FOR
SELECT * FROM HRDB.STOCK_TRANSACTION
WHERE QUANTITY > 9999999;   -- no index on QUANTITY
 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
 

--- STEP 4: TIMING COMPARISON - actually measure the speed difference
   
SET TIMING ON;
 
-- Indexed column - should be fast
SELECT COUNT(*) FROM HRDB.STOCK_TRANSACTION WHERE PRODUCT_ID = 100;
 
-- Non-indexed column - should be noticeably slower (full scan of 1M rows)
SELECT COUNT(*) FROM HRDB.STOCK_TRANSACTION WHERE QUANTITY > 9999999;
 
SET TIMING OFF;
